### PR TITLE
Background Music Added

### PR DESCRIPTION
**Pull request by deepak2431**

### CODE REVIEW

**Comment by deepak2431** [comment]
@amrit-choudhary @vineetjc Please review the background_music also.

**Comment by amrit-choudhary** [comment]
bg music is good
but
make folder structure like this
image
and add your bg music to res/sound/bg

and
change class name of play_sound to
Play_Sound

**Comment by deepak2431** [comment]
Yaa I would close the previous PR.
How can I play the background_music now?

**Comment by amrit-choudhary** [comment]
play_sound class should have three functions.
play_music(music_clip)          # for playing background music, calling it again should change the music
stop_music()                          # for stopping bg music

play_effect(effect_name)       # plays a small sound effect like, coin pickup, bomb sound etc.

**Comment by amrit-choudhary** [comment]
move any sound clip loading to the resources.py file
like this one
self.background_music = pygame.mixer.music.load("res/Music/background_music.mp3")

then the clips are accessed as res.clip.
See how images are done this way.
They are loaded once in resources.py and are used everywhere.

**Comment by deepak2431** [comment]
after loading it into resources.py should I need to remove def __init__()

**Comment by deepak2431** [comment]
Should I load the all the music required to the resources.py and just make different functions in sound_manager.py for their individual effect.

**Comment by amrit-choudhary** [comment]
https://nerdparadise.com/programming/pygame/part3

**Comment by amrit-choudhary** [comment]
@deepak2431  after reviewing the pygame music system, i think what you were doing earlier is better.
There is no need to load in resources.py because pygame can't load and keep music clips for use later, like images. It must load and use music files immediately.

So please make a system like this:
play_sound has these 3 functions:
play_music(music_name)
stop_music()
play_sound(sound_name)

where music_name is a string with the music name, ex. 'bg_music1'
and sound_name is a string with the sound name, ex. 'blast_sound'

in the function, based on the name provided, you will load file from the appropriate location, and play it.

**Comment by deepak2431** [comment]
sound class
main

**Comment by deepak2431** [comment]
@amrit-choudhary I am getting error as music file not loaded what's wrong in this.

**Comment by deepak2431** [comment]
@amrit-choudhary I have followed the above structure but still getting error.What's wrong with the code?

**Comment by amrit-choudhary** [comment]
make a commit and push like yesterday, so that i can check.

**Comment by deepak2431** [comment]
Yeah Sure

**Comment by deepak2431** [comment]
@amrit-choudhary Review #47

**Pull request closed without merging**
