### PR TITLE
New backgrounds and cart sprites

### PR DESCRIPTION
**Pull request by amrit-choudhary**
Added better cart sprites and 10 high quality background sprites.

### CODE REVIEW

**Comment by amrit-choudhary** [comment]
Source: http://spritedatabase.net/file/19530/Backgrounds

**Comment by amrit-choudhary** [comment]
You can pick and choose what you like, then delete rest of them.
Also i can find more bgs similar to what you like.

**Comment by amrit-choudhary** [comment]
code refactoring
1. all classes in different files
2. resources loading is done in a separate class
3. changed main.py to work with the refactoring

**Comment by vineetjc** [comment]
Great work!

Few things:

- Images still waiting review of other peers
- I had to redo some changes I did after merging #9, next time please pull latest changes before sending PR. Not to worry though, it was a minor change.

Awesome!

**Pull request merged**
