### PR TITLE
Add background image to all screens (temporary)

### PR DESCRIPTION
**Pull request by divyang-mittal**

### CODE REVIEW

**Comment by amrit-choudhary** [comment]
Please find and add background images in the project that are suitable for the end and main menu screen.Vinnet can choose which one to show.

**Comment by amrit-choudhary** [comment]
Nice commit, just 3 suggestions
1. Bg blit will replace fill command, because if we have bg there is no need for white fill.
2. Please add bg images as 1024x768 textures and remove the transform command from the code. It will save computation time and also has other benefits.
3. Every menu scene should have a bg, for example tutorial, settings etc.

**Comment by amrit-choudhary** [comment]
White fill = the fill command that’s used 2 lines above the bg blit line.

**Comment by vineetjc** [comment]
@divyang-mittal good work! Before I merge it, I also was about to suggest almost the same things that @amrit-choudhary has, focus on 1 and 2 please. 

- `self.surface.fill(self.res.BGCOLOR)` will be replaced by the `self.surface.blit(self.pygame.transform.scale(self.res.EBG, (1024,768)), (0, 0))`
- If you can put that image on for all menu screens it's good, but I'll take this PR anyway if you improve 1 and 2 for now, but only **for now**.

**Comment by divyang-mittal** [comment]
Thanks for the suggestions. I have remove all the fill lines and transformed all the background images to screen size. Hence removed transform.scale .

**Comment by vineetjc** [comment]
@divyang-mittal good work! Merging PR.

**Pull request merged**
