### PR TITLE
Pull Request Template added and readme updated

### PR DESCRIPTION
**Pull request by deepak2431**

### CODE REVIEW

**Comment by deepak2431** [comment]
How can I make a better GIF any suggestions ?

**Comment by amrit-choudhary** [comment]
also, i have updated the font, so please take the screenshots again.

**Comment by deepak2431** [comment]
Yaa I would change that too.I am facing bit slow network connection problem today .If I could not make PR  today I would make it by  tomorrow.

**Comment by deepak2431** [comment]
@amrit-choudhary  How can I resize the gif?
https://media.giphy.com/media/1wrh15f6gRoHQ3XjRf/giphy.gif
Is this okay?

**Comment by amrit-choudhary** [comment]
yeah, it's okay

**Comment by vineetjc** [comment]
- I must say too that the gif isn't great, the previous one was more fluid. Get a better one if possible.
- I appreciate your effort in putting out a Pull Request Template but it isn't good enough as I read it. Either, take it away from this PR and let this be one just for modifying README, or try to make it a more standard one. I would do it myself otherwise anyway if it's not done by the end of KWoC.

**Comment by deepak2431** [comment]
I would make a better a GIF by adding more images. How can I resize the GIF ?

**Pull request closed without merging**
