### PR TITLE
Background Music Added

### PR DESCRIPTION
**Pull request by deepak2431**

### CODE REVIEW

**Comment by deepak2431** [comment]
Yeah sure I would contact him for that purpose.

**Comment by amrit-choudhary** [comment]
Why are you not following the sound manager design that was suggested on gitter?

**Comment by amrit-choudhary** [comment]
@vineetjc I suggest this structure:

res/sound/bg/             bgmusic1.wav
res/sound/effects/      blast1.wav
res/sound/misc/

res/images/bg/             bg1.png
res/images/objects/     bomb.png
res/images/ui/               button1.png
res/images/misc/          logo.png


res/images/bg/bg1.png

res/images/

**Comment by vineetjc** [comment]
@deepak2431 please check previous comment

**Comment by deepak2431** [comment]
Yeah Sure

**Comment by deepak2431** [comment]
@vineetjc Should I add the same background_music or I shall change it.

**Comment by vineetjc** [comment]
@deepak2431 First I'd suggest following the structure suggested by @amrit-choudhary and then we'll see on changing the music, meanwhile you could find another one as well if you can.

**Comment by deepak2431** [comment]
@amrit-choudhary @vineetjc Sorry I apologise as my vacation has ended so I have to travel back to college.So I was bit busy and could not work.
I tried to add the background _music in which I have done the following changes 
screenshot from 2018-12-13 23-04-28

**Comment by deepak2431** [comment]
After this I import the file in main.py as "from src.managers.sound_manager import play_sound"
It is giving me error as cannot import name play_sound. How can I resolve it?

**Comment by amrit-choudhary** [comment]
@deepak2431  use this
from src.managers.sound_manager import play_sound

do this once
sound_manager = play_sound()
sound_manager.init()

when you want to do anything
sound_manager.play_music()

**Comment by amrit-choudhary** [comment]
i tested this on my main.py, it works

have you taken a pull from the main repo today?

**Comment by deepak2431** [comment]
@amrit-choudhary Yaa I have taken it.My branch is even with the master.

**Comment by deepak2431** [comment]
@amrit-choudhary  after importing the sound_manager.py where I should add the above line in main.py

**Comment by amrit-choudhary** [comment]
image

**Comment by amrit-choudhary** [comment]
and when you want to play something
sound.play_music()
or
sound.play_effect()

**Comment by deepak2431** [comment]
@amrit-choudhary  I have also done the same still getting the same error.

**Comment by amrit-choudhary** [comment]
commit it. so i can see the code

**Comment by deepak2431** [comment]
screenshot from 2018-12-13 23-30-32

**Comment by amrit-choudhary** [comment]
have you saved sound_manager.py?

**Comment by deepak2431** [comment]
Yaa I have saved it.

**Comment by amrit-choudhary** [comment]
just commit and push.

**Comment by deepak2431** [comment]
Ok

**Comment by deepak2431** [comment]
@amrit-choudhary  Review #43

**Pull request closed without merging**
