### PR TITLE
highscore added[not encrypted]

### PR DESCRIPTION
**Pull request by kainthcool**
it shows the high score, but it is saved in a txt file in an unencrypted manner.
i have also added some backgrounds suggestions in images/NewBackgrounds

### CODE REVIEW

**Comment by kainthcool** [comment]
oh! so I need to shift the comparison part in init.

**Comment by kainthcool** [comment]
but the user won't be staying on the game over screen for long, so it won't cause much performance issue.

**Comment by vineetjc** [comment]
@kainthcool Resolve conflicts please

**Comment by kainthcool** [comment]
How to remove them? I am new to all these, can you please guide me a bit.

**Comment by vineetjc** [comment]
@kainthcool just make sure you're updated with the latest version of the repo and then make your changes again and update this PR

**Comment by kainthcool** [comment]
i have resolved conflicts ,please review it

**Comment by vineetjc** [comment]
@kainthcool it's good for now, I merged it, well done!

**Pull request merged**
